module.exports = function (config) {
  config.set({
    basePath: '',
    // Use the Karma plugin provided by the Angular devkit. The
    // '@angular/build' package used by the project does not export a
    // direct 'karma' subpath which leads to a runtime error during test
    // execution. Loading the plugin from '@angular-devkit/build-angular'
    // matches the setup generated by the Angular CLI and prevents the
    // "Package subpath './karma' is not defined" error.
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage')
    ],
    client: {
      clearContext: false
    },
    coverageReporter: {
      dir: require('path').join(__dirname, 'coverage'),
      subdir: '.',
      reporters: [{ type: 'html' }, { type: 'text-summary' }]
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox', '--disable-gpu']
      }
    },
    singleRun: false,
    restartOnFileChange: true
  });
};
